music/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('artists/<int:artist_id>/', views.artist_detail, name='artist_detail'),
    path('albums/<int:album_id>/', views.album_detail, name='album_detail'),
    path('artists/import/', views.artist_import, name='artist_import'),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from drf_spectacular.views import SpectacularAPIView, SpectacularRedocView, SpectacularSwaggerView
from rest_framework.routers import DefaultRouter
from music import viewsets

router = DefaultRouter()
router.register('artists', viewsets.ArtistViewSet)
router.register('albums', viewsets.AlbumViewSet)

urlpatterns = [
    path('music/', include('music.urls')),
    path('admin/', admin.site.urls),
    path('api/v1/', include(router.urls)),
    
    # Archivo YAML con especificación OpenAPI
    path('api/v1/schema/', SpectacularAPIView.as_view(), name='schema'),
    # Documentación Swagger UI
    path('api/v1/schema/swagger-ui/', SpectacularSwaggerView.as_view(url_name='schema'), name='swagger-ui'),
    # Documentación Redoc
    path('api/v1/schema/redoc/', SpectacularRedocView.as_view(url_name='schema'), name='redoc'),
]

# urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)
# urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

music/models.py
from django.db import models

# Create your models here.
class Artist(models.Model):
    name = models.CharField(max_length=200)
    genre = models.CharField(max_length=200)
    image_url = models.CharField(max_length=200, default='https://i.scdn.co/image/ab676161000051747baf6a3e4e70248079e48c5a')

    def __str__(self):
        return self.name

class Album(models.Model):
    artist = models.ForeignKey(Artist, on_delete=models.CASCADE)
    name = models.CharField(max_length=200)
    pub_date = models.DateField('date published')
    image_url = models.CharField(max_length=200, default='https://community.spotify.com/t5/image/serverpage/image-id/55829iC2AD64ADB887E2A5?v=v2')

    def __str__(self):
        return f"{self.artist} - {self.name}"

music/forms.py
from django import forms
from music.models import Artist, Album

class ArtistForm(forms.ModelForm):
    class Meta:
        model = Artist
        fields = "__all__"

class AlbumForm(forms.ModelForm):
    class Meta:
        model = Album
        fields = "__all__"

class ImportForm(forms.Form):
    artist_id = forms.IntegerField()
    import_artist = forms.BooleanField(required=False)

music/views.py
from django.shortcuts import render
from django.http import HttpResponse
from music.forms import ArtistForm, AlbumForm, ImportForm
from music.models import Artist, Album
import requests

def index(request):
    artists = Artist.objects.all()
    context = {'artists': artists}
    return render(request, 'music/index.html', context)

def artist_detail(request, artist_id):
    artist = Artist.objects.get(id=artist_id)
    if request.method == 'POST':
        form = ArtistForm(request.POST, instance=artist)
        if form.is_valid():
            artist = form.save()
    else:
        form = ArtistForm(instance=artist)

    context = {'artist': artist, 'form': form}
    return render(request, 'music/artist_detail.html', context)

def album_detail(request, album_id):
    album = Album.objects.get(id=album_id)
    if request.method == 'POST':
        form = AlbumForm(request.POST, instance=album)
        if form.is_valid():
            album = form.save()
    else:
        form = AlbumForm(instance=album)

    context = {'album': album, 'form': form}
    return render(request, 'music/album_detail.html', context)

def artist_import(request):
    artist_data = None
    if request.method == 'POST':
        form = ImportForm(request.POST)
        if form.is_valid():
            artist_id = form.cleaned_data['artist_id']
            url = f"https://api.discogs.com/artists/{artist_id}" 
            artist_data = requests.get(url).json()
            if form.cleaned_data['import_artist']:
                Artist.objects.create(name=artist_data['name'], genre="No disponible")
        print("hola")
    else:
        form = ImportForm()
    context = {'form': form, 'artist': artist_data}
    return render(request, 'music/artist_import.html', context)

music/templates/music/album_detail.html
{% extends "music/base.html" %}

{% block title %}
<title>{{ album }}</title>
{% endblock %}

{% block content %}
<section id="album-page">
    <h2>{{ album.name }}</h2>
    <div class="album-container">
        <img src="{{album.image_url}}" alt="{{album}}">
        <div class="info-album">
            <a href="{% url 'artist_detail' album.artist_id %}">{{album.artist}}</a>
            <p class="album-year">{{album.pub_date|date:"Y"}}</p>
        </div>
    </div>
    <div class="shadow"></div>
</section>
<section>
    <h2>Editar Álbum</h2>
    <form  class="edit-form" action="{% url 'album_detail' album.id %}" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input class="guardar" type="submit" value="Guardar">
    </form>
    <div class="shadow"></div>
</section>
{% endblock %}

music/templates/music/artist_detail.html
{% extends "music/base.html" %}

{% block title %}
<title>{{ artist }}</title>
{% endblock %}

{% block content %}
<section id="artist-page">
    <h2>{{ artist }}</h2>
    <div class="artist-container">
        <div class="artist-img-container">
            <img class="artist-img" src="{{ artist.image_url }}" alt="imagen de {{artist}}">
        </div>
        <div>
            <h3>Género: <span class="genre">{{artist.genre}}</span></h3>
            <h3>Álbumes:</h3>
            <ul class="albums-list">
                {% for album in artist.album_set.all|dictsortreversed:"pub_date" %}
                <li><a href="{% url 'album_detail' album.id %}">· {{ album.name }} - {{album.pub_date|date:"Y"}}</a></li>
                {% endfor %}
            </ul>
        </div>
    </div>
    <div class="shadow"></div>
</section>
<section>
    <h2>Editar Artista</h2>
    <form id="artist-form" data-artist-id="{{ artist.id }}" class="edit-form" action="{% url 'artist_detail' artist.id %}" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input class="guardar" type="submit" value="Guardar">
    </form>
    <div class="shadow"></div>
</section>
{% endblock %}

music/templates/music/artist_import.html
{% extends 'music/base.html' %} 
{% block content %}
    <form class="form-import" action="{% url 'artist_import' %}" method="post"> 
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Go">
    </form>
<p class="artist-import">
    {{ artist | default:"" }}
</p>
{% endblock %}

music/templates/music/base.html
<!DOCTYPE html>
<html>

<head>
    {% block title %}<title>Music App</title>{% endblock %}
    <meta charset="UTF-8" />
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'music/style.css' %}" />
    <script src="{% static 'music/script.js' %}"></script>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.2/css/all.min.css" integrity="sha512-z3gLpd7yknf1YoNbCzqRKc4qyor8gaKU1qmn+CShxbuBusANI9QpRohGBreCFkKxLhei6S9CQXFEbbKuqLg0DA==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@300;400;500;700;900&display=swap" rel="stylesheet">
</head>

<body>
    <header>
        <a href="{% url 'index' %}"><i class="fa-solid fa-play"></i><h1>Music App</h1></a>
    </header>

    <main>
        <nav>
            <ul class="nav-list">
                <li class="nav-list-item">
                    <p>Menú</p>
                </li>
                <li class="nav-list-item">
                    <i class="fa-solid fa-user"></i>
                    <a href="#">Artistas</a>
                </li>
                <li class="nav-list-item">
                    <i class="fa-solid fa-layer-group"></i>
                    <a href="#">Álbumes</a>
                </li>
                <li class="nav-list-item">
                    <i class="fa-solid fa-ticket"></i>
                    <a href="#">Conciertos</a>
                </li>
                <li class="nav-list-item">
                    <i class="fa-solid fa-video"></i>
                    <a href="#">Videos</a>
                </li>
            </ul>
        </nav>

        {% block content %}
        {% endblock %}    

    </main>
    <footer>
        <div class="footer-container-up">
            <div class="footer-left">
                <img class="album-thumbnail" src="https://i.scdn.co/image/ab67616d0000b2736b915e407b70e121e06fe979" alt="">
                <div>
                    <h3 class="album-title">New Rules</h3>
                    <p>Dua Lipa</p>
                </div>
            </div>
            <div class="footer-center">
                <div class="footer-center-top">
                    <i class="fa-solid fa-rotate-left"></i>
                    <i class="fa-solid fa-step-backward"></i>
                    <div class="play-main">
                        <i class="fa-solid fa-play"></i>
                    </div>
                    <i class="fa-solid fa-step-forward"></i>
                    <i class="fa-solid fa-rotate-right"></i>
                </div>
                <div class="footer-center-bottom">
                    <p>0:33</p>
                    <div class="progress-bar">
                        <div class="progress-bar-fill"></div>
                    </div>
                    <p>3:29</p>
                </div>
            </div>
            <div class="footer-right">
                <i class="fa-solid fa-list"></i>
                <i class="fa-solid fa-volume-high"></i>
                <div class="volume-bar">
                    <div class="volume-bar-fill"></div>
                </div>
                <i class="fa-solid fa-up-right-and-down-left-from-center"></i>
            </div>
        </div>
        <div class="footer-container-bottom">
            <p>
                Copyright © Python y la Web, 2023. <span>Más información <a href="https://ep.ingenieriauc.cl/course/view.php?id=4150">en la página de La Clase Ejecutiva.</a></span>
            </p>
        </div>
    </footer>
</body>
</html>

music/templates/music/index.html
{% extends "music/base.html" %}

{% block title %}
<title>Music App</title>
{% endblock %}

{% block content %}
<section>
    <h2>Artistas</h2>
        <ol class="artistas-container"> 
            {% for artist in artists %}
            <li>
                <div class="artista-item">
                    <img src="{{artist.image_url}}" alt="imagen de {{artist}}">
                    <a href="{% url 'artist_detail' artist.id %}">{{artist}}</a>
                    <div class="play"><i class="fa-solid fa-play"></i></div>
                </div>
            </li>
            {% endfor %}
        </ol>
    <div class="shadow"></div>
</section>
<section>
    <h2>Álbumes</h2>
    <table>
        <thead>
            <tr>
                <th>Artista</th>
                <th>Álbum</th>
                <th>Año</th>
            </tr>
        </thead>
        {% for artist in artists %}
            <tbody>
                {% for album in artist.album_set.all|dictsortreversed:"pub_date" %}
                    {% if forloop.counter == 1 %}
                        <tr>
                            <td rowspan="{{ artist.album_set.all|length }}"><a href="{% url 'artist_detail' artist.id %}">{{artist}}</a></td>
                    {% endif %}
                        <td><a href="{% url 'album_detail' album.id %}">{{album.name}}</a></td>
                        <td>{{album.pub_date|date:"Y"}}</td>
                    </tr>
                {% endfor %}
            </tbody>
        {% endfor %}
    </table>
    <div class="shadow"></div>
</section>
{% endblock %}